version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pessoas_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pessoas_network

volumes:
  postgres_data:

networks:
  pessoas_network:
    driver: bridge